import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Esquema inicial: tabla `book`.
 *
 * Se escribe a mano en lugar de generarla, para poder documentar por qué cada
 * columna es como es y añadir las restricciones que el enunciado pide como
 * reglas de negocio (coste positivo, stock no negativo) también en la base de
 * datos, no sólo en los DTO.
 */
export class EsquemaInicial1791234000000 implements MigrationInterface {
  name = 'EsquemaInicial1791234000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "book" (
        "id"                  integer GENERATED BY DEFAULT AS IDENTITY,
        "title"               varchar(255)  NOT NULL,
        "author"              varchar(255)  NOT NULL,
        "isbn"                varchar(20)   NOT NULL,
        "isbn_normalizado"    varchar(13)   NOT NULL,
        "cost_usd"            numeric(10,2) NOT NULL,
        "selling_price_local" numeric(12,2),
        "stock_quantity"      integer       NOT NULL,
        "category"            varchar(120)  NOT NULL,
        "supplier_country"    char(2)       NOT NULL,
        "created_at"          timestamptz   NOT NULL DEFAULT now(),
        "updated_at"          timestamptz   NOT NULL DEFAULT now(),
        CONSTRAINT "PK_book" PRIMARY KEY ("id"),
        CONSTRAINT "CHK_book_cost_usd_positivo"   CHECK ("cost_usd" > 0),
        CONSTRAINT "CHK_book_stock_no_negativo"   CHECK ("stock_quantity" >= 0),
        CONSTRAINT "CHK_book_precio_venta_positivo"
          CHECK ("selling_price_local" IS NULL OR "selling_price_local" > 0),
        CONSTRAINT "CHK_book_isbn_normalizado_formato"
          CHECK ("isbn_normalizado" ~ '^[0-9]{13}$' OR "isbn_normalizado" ~ '^[0-9]{9}[0-9X]$')
      )
    `);

    // La unicidad se impone sobre el ISBN normalizado, no sobre el original:
    // si no, "978-84-376-0494-7" y "9788437604947" serían dos libros.
    await queryRunner.query(`
      CREATE UNIQUE INDEX "UQ_book_isbn_normalizado" ON "book" ("isbn_normalizado")
    `);

    // Índices sobre lo que el listado filtra de verdad.
    await queryRunner.query(`CREATE INDEX "IDX_book_category" ON "book" ("category")`);
    await queryRunner.query(`CREATE INDEX "IDX_book_stock_quantity" ON "book" ("stock_quantity")`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "book"`);
  }
}
